server {
    listen 80;
    root /usr/share/nginx/html;
    index pagina-principal.html;

    location / {
        try_files $uri $uri/ /pagina-principal.html;
    }

    # Admin API proxy
    location /api/admin/ {
        proxy_pass http://admin:5050/api/admin/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
